### ISSUE TITLE
Setup Beats-Tester on Jenkins Slave

### ISSUE THREAD

**Issue by ruflin** [elastic/beats-tester#10]
Beats-Tester should run on all new builds. For this it needs to be installed on a raw metal machine. This issue is to document / track changes and issues which occurred.

**Comment by ruflin** [comment]
Installation:
 * Default Ubuntu version does not work. Old version uninstalled and most recent version [downloaded](http://download.virtualbox.org/virtualbox/5.0.8/virtualbox-5.0_5.0.8-103449~Ubuntu~trusty_i386.deb) and installed
*

**Comment by ruflin** [comment]
@dliappis FYI

**Comment by dliappis** [comment]
Going forward do you mind if we setup those tests to run under the `jenkins` user?

As we hooked `bt00.build.ci.hetz.es.io` in build-eu-00 it makes sense to agree that the tests will run under the dedicated user. Additionally it makes things like pip/virtualenv installation cleaner.

Let me summarize from memory:

- latest version of virtualbox (5.x seems to work fine)
- As you said, latest version of vagrant
- Latest ansible in 1.9.x branch
- Install pywinrm with pip; would you prefer having a virtualenv python environment for the user jenkins that you source prior to running your job or just `pip install --user pywinrm` in which case we also need to ensure ~/.local/bin is in the `$PATH`; from my experience using virtualenv is better

Running `make beta4` could serve as a unit test?

I assume this repo: https://github.com/elastic/beats-tester needs to be cloned before doing make beat4. Any particular ssh deploy key we should be aware of?

**Comment by ruflin** [comment]
All the above is correct. Jenkins user sounds good, as long as no special permissions for vagrant / virtualbox are needed. For the pywinrm installation go for the simpler solution for you. 

Before make beat4 the repo must be cloned. As all the repos are public, no special keys are necessary. I assume we can follow here the same workflow as we do for all other repos in Jenkins.

Let me know if you need some more details.

**Comment by ruflin** [comment]
Beats tester is now running every 24 hours with the latest builds on the hetzner machine: http://build-eu-00.elastic.co/view/Beats/job/beats-tester/ Closing this now.
