### ISSUE TITLE
Update for ansible 2.9.x for beats-tester

### ISSUE THREAD

**Issue by mikemadden42** [elastic/beats-tester#144]
Ansible 2.9.0 has been released.  We need to ensure this works with `beats-tester`.

https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.9.html

**Comment by mikemadden42** [comment]
ansible `2.9.2` is the current release.

**Comment by v1v** [comment]
Wait for https://github.com/elastic/beats-tester/issues/155 to enable PR validations automatically

**Comment by v1v** [comment]
Already agreed to close this issue since it's not required
